# Generated by Django 4.0 on 2022-01-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateField(verbose_name='day')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_name', models.CharField(max_length=20, verbose_name='name')),
                ('pupil_surname', models.CharField(blank=True, max_length=20, verbose_name='lname')),
                ('pupils_father', models.CharField(blank=True, max_length=20, verbose_name='fname')),
                ('theme', models.CharField(blank=True, max_length=30, verbose_name='theme')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='was created')),
                ('time', models.TimeField(verbose_name='time')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='calendary.day')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-created_at'],
            },
        ),
    ]
